// SPDX-License-Identifier: GPL-3.0-or-later

// Package ptnop allows composing observable network measurement pipelines.
//
// This package is built around:
//
//  1. the [*Config] struct containing the pipeline configuration.
//
//  2. the [Func] interface and the [Compose2] ... [Compose8] function composition primitives.
//
//  3. constructors for network operations such as [NewConnectFunc].
//
// From these primitives, one can build a pipeline of operations. Pipelines always yield
// a persistent network connection to a remote endpoint speaking a given protocol.
//
// For example, by composing these primitives:
//
//   - [ConnectFunc]
//   - [TLSHandshakeFunc]
//   - [HTTPConnFunc]
//
// One obtains a persistent HTTPS connection to a remote host, which has a RoundTrip
// method to perform round trips and a Close method to close the conn.
//
// The [*Config] contains an [SLogger] field that configures a [log/slog] like
// logger. While the default implementation does not log, if you override it with
// a real [*log/slog.Logger], you get structured events covering:
//
//  1. TCP/UDP connection establishment
//  2. I/O events (read, write, set deadline, close)
//  3. TLS handshake events
//  4. HTTP round trip events
//  5. DNS exchange events
//
// All the above events are at [log/slog.LevelInfo] level except for I/O events
// which are emitted at the [log/slog.LevelDebug] level.
//
// Each pipeline stage that may fail returns a [Result] type containing either
// the on-success value or an error with either-or semantics. Subsequent
// stages keep running on failure and must check the [Result] value state.
//
// With the exception of I/O events, all other events are produced even when the
// previous pipeline stage failed. This design choice ensures that it is always
// possible to reconstruct ex-post what the pipeline wanted to do, regardless of
// whether there were early failures. For example, assuming this pipeline:
//
//   - [ConnectFunc]
//   - [TLSHandshakeFunc]
//   - [HTTPConnFunc]
//
// even if [ConnectFunc] fails you still see [TLSHandshakeFunc] and
// [HTTPConnFunc] generated events showing what would have been done had
// the previous stages succeeded.
//
// This particular condition when a stage runs when the previous stage
// failed is marked with the [ErrSkip] error.
//
// We classify all errors in the structured log using [DefaultErrClassifier] by
// default. This classifier is such that, when [ErrSkip] is the error, the
// corresponding `errClass` field value is "ESKIP".
//
// All in all, this design allows a machine consumer to parse the event
// stream generated by a pipeline and transform it into a tabular data
// structure (e.g. parquet), where every row has every column filled and
// skipped stages are marked as "ESKIP". Thus, for example, it
// is obvious which failed rows belong to, say, TLS handshakes that would
// have been made to send specific HTTP requests, versus, say, TLS handshakes
// that were motivated by sending DNS-over-TLS requests.
//
// As a caveat, some I/O events (e.g. closeStart/Done and readDone
// events) may be emitted after the code running the pipeline has returned
// when using [net/http]. This happens because [net/http] manages the
// conn in a background goroutine and closes it asynchronously. Thus, a tool
// that exits when its pipelines are done might miss these events.
//
// To distinguish between the output of multiple pipelines, it is advised to
// use [log/slog.Logger.With], so that each pipeline is bound to a unique
// identifier (for example a UUIDv4 or a UUIDv7).
//
// # Func axioms
//
//  1. every [Func] that receives a [Result] containing an error must
//     eventually return an [ErrSkip] wrapping the error
//
//  2. regardless of [ErrSkip] or other errors, the [Func] must run
//     to completion and emit events, obviously skipping any network
//     operation that would have been run if possible
//
//  3. if the [Func] receives a struct with a `Close` method and
//     fails such that it would return a [Result] containing an
//     error, then it invokes the `Close` method; otherwise, the
//     ownership is passed to the next stage
//
// # Timing out
//
// You should always include [CancelWatchFunc] in your pipeline to
// interrupt network operations when the context is canceled.
//
// # HTTP vs HTTPS
//
// The [HTTPConnFunc] takes in input a [net.Conn] and checks whether
// such a conn implements [TLSConn]. If that is the case, then it uses
// the HTTPS protocol; otherwise, it uses HTTP. Hence, when you want
// to use HTTPS, the previous stage must be [TLSHandshakeFunc].
//
// # Complex measurements
//
// Even something as simple as measuring https://www.example.com/
// entails complex operations: DNS lookup, and then a TCP + TLS + HTTP
// pipeline for each resolved endpoint. This package does not tell
// you how to compose these operations and it's up to you to decide
// whether, for example, you want to test all the resolved endpoints,
// just the first one, one IPv4 and one IPv6 endpoint, etc.
//
// The only thing that this package provides you with is the ability
// to define a single pipeline, with a single possible failure,
// that runs end-to-end and always produces the same major events
// (connect, TLS, HTTP, DNS) regardless of intermediate errors,
// so that later on you can create tabular results.
//
// All other concerns are policy concerns that are outside of the
// scope of this package and up to you, the user.
//
// # Mutability
//
// Structs can be modified before use. Do not modify them once
// you have used them, to avoid potential data races.
//
// Mutating interface fields of structs by type asserting is not
// how we expect you to use this library. In particular, this may
// cause mutation of globals, which will cause data races.
//
// If you follow the above rules, this package is goroutine safe.
//
// # Lazy carriers
//
// The [*HTTPConn] and the [DNSConn] types carry the [Result]
// inside them so that you notice the actual failure when
// attempting to perform the related operation. That is, the
// fact that [*HTTPConnFunc] always returns [*HTTPConn]
// doesn't mean that it always succeeds. It means that the
// error, if any, is observed when calling the [*HTTPConn.RoundTrip]
// method such that the related events may be emitted.
//
// Close on a lazy carrier whose [Result] holds an error is a
// no-op: there is nothing to close.
//
// # HTTP body events
//
// [*HTTPConn.RoundTrip] automatically returns an [*net/http.Response]
// where the Body field is an [*HTTPBodyWrapper] so that by
// reading the body you also generate the related structured
// logs as a side effect. If this annoys you, you can type
// assert for [*HTTPBodyWrapper]: its Body field is public and
// carries the original [*net/http.Response] body.
//
// # Skipped pipeline error
//
// When a complex pipeline fails midway, the returned error is
// an instance of [ErrSkip], possibly with multiple levels of
// [ErrSkip] wrapping. Because [ErrSkip] does not modify the string
// representation of the error and it implements the golang unwrap
// protocol for errors, you won't notice this unless you try to
// classify the returned error. In such a case, you will see the
// "ESKIP" value because the outer layer is an [ErrSkip].
//
// So, if your aim is to classify the overall pipeline outcome
// based on the error of the final operation you perform, you
// need to recursively unwrap [ErrSkip] first, just in case, so
// that you get the actual error classification.
package ptnop
